### ISSUE TITLE
Gateway Wireless json definition does not display

### ISSUE THREAD

**Issue by bsilverajan** [T4ACTIVE/T4ACTIVE.github.io#13]
When browsing through the gateway wireless LWM2M model, the json definition does not seem to display at all. The html code is the same as the one in Gateway System, but points instead to Gateway_Wireless.json

However it still does not display any json definitions. @Hanningz can you please check what's wrong?

**Comment by Hanningz** [comment]
Sorry for the problem, it is because I removed the JS code for reading JSON file this afternoon since I thought there is no JSON file there, now it is displayed.

**Comment by bsilverajan** [comment]
Thanks, it works now!
